print("Введите три числа")
a = input("число а=")
print(a)
b = input("число b=")
print(b)
c = input("число c=")
print(c)
d=round((int(a)+int(b)+int(c))/3,3)
print(f"Среднее арифметическое ваших чисел {d}")

